package com.welearn.domain.entities;
// Generated 26 Jan, 2018 7:24:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Admins generated by hbm2java
 */
public class Admins  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private Date lastLogin;

    public Admins() {
    }

    public Admins(String username, String password, Date lastLogin) {
       this.username = username;
       this.password = password;
       this.lastLogin = lastLogin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }




}


