package com.welearn.domain.entities;
// Generated 26 Jan, 2018 7:24:21 AM by Hibernate Tools 4.3.1



/**
 * Answers generated by hbm2java
 */
public class Answers  implements java.io.Serializable {


     private Integer id;
     private int quizId;
     private int questionId;
     private String answer;
     private String correct;

    public Answers() {
    }

    public Answers(int quizId, int questionId, String answer, String correct) {
       this.quizId = quizId;
       this.questionId = questionId;
       this.answer = answer;
       this.correct = correct;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(int quizId) {
        this.quizId = quizId;
    }
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }
    public String getCorrect() {
        return this.correct;
    }
    
    public void setCorrect(String correct) {
        this.correct = correct;
    }




}


