package com.welearn.domain.entities;
// Generated 26 Jan, 2018 7:24:21 AM by Hibernate Tools 4.3.1



/**
 * Questions generated by hbm2java
 */
public class Questions  implements java.io.Serializable {


     private Integer id;
     private int quizId;
     private int questionId;
     private String question;
     private String code;
     private String codeType;
     private String type;

    public Questions() {
    }

    public Questions(int quizId, int questionId, String question, String code, String codeType, String type) {
       this.quizId = quizId;
       this.questionId = questionId;
       this.question = question;
       this.code = code;
       this.codeType = codeType;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(int quizId) {
        this.quizId = quizId;
    }
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getCodeType() {
        return this.codeType;
    }
    
    public void setCodeType(String codeType) {
        this.codeType = codeType;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


