package com.welearn.domain.entities;
// Generated 26 Jan, 2018 7:24:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * QuizTakers generated by hbm2java
 */
public class QuizTakers  implements java.io.Serializable {


     private Integer id;
     private String username;
     private int quizId;
     private int marks;
     private String percentage;
     private Date dateTime;
     private int duration;

    public QuizTakers() {
    }

    public QuizTakers(String username, int quizId, int marks, String percentage, Date dateTime, int duration) {
       this.username = username;
       this.quizId = quizId;
       this.marks = marks;
       this.percentage = percentage;
       this.dateTime = dateTime;
       this.duration = duration;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public int getQuizId() {
        return this.quizId;
    }
    
    public void setQuizId(int quizId) {
        this.quizId = quizId;
    }
    public int getMarks() {
        return this.marks;
    }
    
    public void setMarks(int marks) {
        this.marks = marks;
    }
    public String getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(String percentage) {
        this.percentage = percentage;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }




}


